--- 
- name: deploy kong api gateway
 
  hosts: all
  tasks: 
    - name: install docker via snap
      command: snap install docker
    - name: pull the kong docker
      command: docker pull kong/kong-gateway:2.7.0.0-alpine
    - name: tag
      command: docker tag kong/kong-gateway:2.7.0.0-alpine kong
    - name: Create a Docker network
      command: docker network create kong-net
    - name: Start and prepare Postgres DB
      command: docker run -d --name kong-database --network=kong-net -e "POSTGRES_USER=kong" -e "POSTGRES_DB=kong" -e "POSTGRES_PASSWORD=kong" -p 5432:5432 postgres:9.6
    - name: run
      command: docker run --rm --network=kong-net -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_PG_PASSWORD=kong" kong:latest kong migrations bootstrap
    - name: Start kong
      command: docker run -d --name kong --network=kong-net -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -e "KONG_PG_PASSWORD=kong" -e "KONG_PROXY_ACCESS_LOG=/dev/stdout" -e "KONG_ADMIN_ACCESS_LOG=/dev/stdout" -e "KONG_PROXY_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_ERROR_LOG=/dev/stderr" -e "KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl" -p 8000:8000 -p 8443:8443 -p 8001:8001 -p 8444:8444 kong:latest
